% Set default values for plots to make them look nicer

set(0, ...
    'DefaultFigureColor', 'White', ...
    'DefaultFigurePaperType', 'a4letter', ...
    'DefaultAxesColor', 'white', ...
    'DefaultAxesFontUnits', 'points', ...
    'DefaultAxesFontSize', 15, ... 
    'DefaultLineLineStyle', '-', ...
     'DefaultLineLineWidth', 2, ...
    'DefaultLineMarker', 'none', ...
    'DefaultLineMarkerSize', 8, ...
    'DefaultTextFontUnits', 'Points', ...
    'DefaultTextFontSize', 14, ...
    'DefaultTextinterpreter','latex');
