

mex CXXFLAGS="\$CXXFLAGS -msse4.1 -falign-loops=16 -Wall -fopenmp" ...
    DYLDFLAGS="\$DYLDFLAGS -fopenmp" mex_Trap2GL.c 

mex CXXFLAGS="\$CXXFLAGS -msse4.1 -falign-loops=16 -Wall -fopenmp" ...
    DYLDFLAGS="\$DYLDFLAGS -fopenmp" mex_dospecquad3.cpp  

mex CXXFLAGS="\$CXXFLAGS -msse3 -falign-loops=16 -Wall -fopenmp" CFLAGS="-msse3 -fPIC"...
    DYLDFLAGS="\$DYLDFLAGS -fopenmp" mex_M1M4.c

mex CXXFLAGS="\$CXXFLAGS -msse3 -falign-loops=16 -Wall -fopenmp" CFLAGS="-msse3 -fPIC"...
    DYLDFLAGS="\$DYLDFLAGS -fopenmp" mex_M1M5.c

mex CXXFLAGS="\$CXXFLAGS -msse3 -falign-loops=16 -Wall -fopenmp" CFLAGS="-msse3 -fPIC"...
    DYLDFLAGS="\$DYLDFLAGS -fopenmp" mex_M1.c

mex CXXFLAGS="\$CXXFLAGS -msse4.1 -falign-loops=16 -Wall -fopenmp" ...
    DYLDFLAGS="\$DYLDFLAGS -fopenmp" mex_applymodifs.cpp 

mex CXXFLAGS="\$CXXFLAGS -msse4.1 -falign-loops=16 -Wall -fopenmp" ...
    DYLDFLAGS="\$DYLDFLAGS -fopenmp" mex_Trap2GL_real.c 

mex CXXFLAGS="\$CXXFLAGS -msse4.1 -falign-loops=16 -Wall -fopenmp" ...
    DYLDFLAGS="\$DYLDFLAGS -fopenmp" mex_gmresinner_el.c
